// +build ignore

package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
)

func mustreadfile(name string) []byte {
	b, err := ioutil.ReadFile(name)
	if err != nil {
		log.Fatal(err)
	}
	return b
}

func main() {
	vert := mustreadfile("environment-vert.glsl")
	frag := mustreadfile("environment-frag.glsl")

	buf := new(bytes.Buffer)
	buf.WriteString("// generated by gen.go; DO NOT EDIT\npackage assets\n\n")
	fmt.Fprintf(buf, "var VertexShader = `%s`\n\n", string(vert))
	fmt.Fprintf(buf, "var FragmentShader = `%s`\n", string(frag))
	if err := ioutil.WriteFile("glsl.go", buf.Bytes(), 0644); err != nil {
		log.Fatal(err)
	}
}
