// +build ignore

package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"strconv"
)

const tmpl = `// File is automatically generated by genout.go. DO NOT EDIT.

package text

var Texture = []byte(%s)`

func main() {
	b, err := ioutil.ReadFile("out.png")
	if err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("out.go", []byte(fmt.Sprintf(tmpl, strconv.Quote(string(b)))), 0644); err != nil {
		log.Fatal(err)
	}
}
